sylius_mailer:
    emails:
        trustpilot_email:
            subject: setono_sylius_trustpilot.emails.trustpilot.subject
            template: "@SetonoSyliusTrustpilotPlugin/Email/trustpilot.html.twig"
